#
# Since hypixel uses it's own protocol system to support newer clients, It will be filtered out from tampering with versions.
#
client-side-force-disable:
- hypixel.net
- '*.hypixel.net'
#
# Manages the version protocol for servers, Please keep in mind that the author of ViaFabric is NOT responsible for unexpected punishments,
# based of this mod. If you happen to get banned with this then you're basically on your own entirely!
#
client-side-version: -2
enable-client-side: true
hide-button: false
