# Dyanmic lights configuration,
# It is recommended you leave this mode set to fancy for best effects unless your game lags out or crashes with this mod, Then please remove this from your profile.
mode = "fancy"

# Light sources configuration, Can be modified if you wish to use your own choices.
[light_sources]
	# Prevents torches and other entities from lighting up when submerged into water sources.
	water_sensitive_check = true
	# Should block entities light up?
	block_entities = false
	# Should entities light up?
	entities = false
	# TNT will be brighter when ignited, May not be recommended to turn this on.
	tnt = "off"
	# Creepers will be brighter when ignited, May not be recommended to turn this on.
	creeper = "off"

